// Generated by CoffeeScript 1.7.1
module.exports = function(msg, session, next) {
  next.success = function() {
    return next(null, {
      _r: 's'
    });
  };
  next.suc = next.success;
  next.fail = function(msg, code) {
    if (code == null) {
      code = "1";
    }
    return next(null, {
      _r: code,
      _m: msg
    });
  };
  next.err = next.fail;
  return next.server_err = function() {
    return next(null, {
      _r: "1",
      _m: "服务器出问题啦"
    });
  };
};
