// Generated by CoffeeScript 1.7.1
module.exports = function(app, mongoose, Schema) {
  var UserBase, UserBaseSchema;
  UserBaseSchema = new Schema({
    username: {
      type: String,
      required: true,
      index: {
        unique: true
      }
    },
    password: String,
    created_at: String,
    is_online: Boolean
  });
  UserBaseSchema.methods.set_online = function(cb) {
    return this.update({
      online: true
    }, cb);
  };
  UserBase = mongoose.model('UserBase', UserBaseSchema);
  return app.models.UserBase = UserBase;
};
