// Generated by CoffeeScript 1.7.1
module.exports = function(app, mongoose, Schema) {
  var UserInfoSchema;
  return UserInfoSchema = new Schema({
    silver: Number,
    gold: Number,
    ps: Number,
    base: {
      type: Schema.Types.ObjectId,
      ref: 'UserBase'
    }
  });
};
