// Generated by CoffeeScript 1.7.1
module.exports = function(app, mongoose, Schema) {
  var UserInfo, UserInfoSchema;
  UserInfoSchema = new Schema({
    score: Number,
    "default": 0,
    icon: String,
    level: Number,
    "default": 0,
    name: String,
    desc: String
  });
  UserInfo = mongoose.model('user_info', UserInfoSchema);
  return app.models.UserInfo = UserInfo;
};
